### ISSUE TITLE
As a customer, I need a shopping cart, so that I can collect items I want to buy

### ISSUE THREAD

**Issue by collin** [collins-example-team/our-grace-shopper#1]
- [x] API endpoint: `GET /shopping-cart` returns list of items current in cart
- [x] `POST /shopping-cart/items` adds a product to the cart
- [x] `<Cart>` component to show the items in the cart
- [x] `<MenuCart>` to show how many items are in the cart in the header menu
- [ ] **Write some tests, for the love of god!**

**Comment by weblemur** [comment]
- [ ] `npm install grace-shopper`
